---
version: 2

updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
    groups:
      bundler-dependencies:
        applies-to: version-updates
        update-types:
          - minor
          - patch
      bundler-security:
        applies-to: security-updates
        patterns:
          - '*'
    cooldown:
      default-days: 5

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    groups:
      npm-dependencies:
        applies-to: version-updates
        update-types:
          - minor
          - patch
      npm-security:
        applies-to: security-updates
        patterns:
          - '*'
    cooldown:
      default-days: 5

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: '02:00'
      timezone: 'Etc/UTC'
