search:
  paths:
    - "app/controllers"
    - "app/helpers"
    - "app/pages"
    - "app/views"
  exclude:
    - "app/views/administrate/kaminari"

data:
  read:
    - config/locales/administrate.%{locale}.yml

ignore_unused:
  - activerecord.*
  - administrate.*
  - date.*
  - simple_form.*
  - time.*
  - titles.*
